### ISSUE TITLE
Difference in lanelet2_matching and searching region inside bounding box 

### ISSUE THREAD

**Issue by Wing-ka-king** [coincar-sim/lanelet2_matching#1]
Hi! Need some help with implementation of the functions.
Among the examples provided with lanelet2 package, the search function has been shown to work on lanelet layer with bounding boxes. `Lanelets inRegion = laneletMap.laneletLayer.search(BoundingBox2d(BasicPoint2d(0, 0), BasicPoint2d(10, 10)));`
Can you elaborate on why and where should I prefer using lanelet2_matching 's functions?

Also, in order to get the lanelet where my object is currently located, do I simply have to reduce the distance in 
`// retrieve lanelet matches from map`
`auto detMatches = getDeterministicMatches(laneletMap, obj, 4.); // max distance = 4m`
`auto probMatches = getProbabilisticMatches(laneletMap, obj2, 4.); // max distance = 4m`
but I still get mutiple lanelets in the returned vector.

Thank you!

**Comment by m-naumann** [comment]
Hi

>  Can you elaborate on why and where should I prefer using lanelet2_matching 's functions?

`lanelet2_matching` supports matching of objects with a hull, and includes probabilistic matching and traffic rule compliance checking (driving against the direction of travel, pedestrian lanelets are forbidden for vehicles, ...). Furthermore it is unittested. That's why we use it internally and encourage others to use it when matching objects (vehicles, pedestrians, cyclists) to lanelets.

>  but I still get multiple lanelets in the returned vector.

This is intended. If lanelets overlap, multiple lanelets could be correct. 
![image](https://user-images.githubusercontent.com/22504347/103530380-960e4080-4e87-11eb-96dd-9e761151d97b.png)

A vehicle at "K" for example could be in lanelet K and turning right into G, or it could be in D and driving straight into F. Or it could be in lanelet I when driving from E to G. Depending on the orientation, the probabilistic matching function will assign probabilities to those possibilities.

**Comment by Wing-ka-king** [comment]
Well said! 
But from your experience would you recommend keeping max distance as width of the lanes, in order to match the vehicles to their lanes or some other metric?

**Comment by m-naumann** [comment]
That depends on your localization and perception quality. If both was perfect, you can use 0. If you have errors in the range of 1m, use 1, and so on.
